stable/nfs-client-provisioner/Chart.yaml
stable/nfs-client-provisioner/README.md
stable/nfs-client-provisioner/templates/storageclass.yaml
stable/nfs-client-provisioner/values.yaml

Closing out issue #10 
Default stays the same, but can now add storageClass.reclaimPolicy='retain'

add reclaimPolicy

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/values.yaml

update gcloud-sqlproxy to new version, comment out resources

---

stable/contour/Chart.yaml
stable/contour/templates/NOTES.txt
stable/contour/templates/clusterrolebinding.yaml
stable/contour/templates/deployment.yaml
stable/contour/templates/namespace.yaml
stable/contour/templates/service.yaml
stable/contour/templates/serviceaccount.yaml
stable/contour/values.yaml
stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md

remove hardcoded namespace for contour, update gcloud-sqlproxy readme

---

stable/contour/Chart.yaml

fix contour logo url

---

stable/gke-pvm-killer/Chart.yaml
stable/gke-pvm-killer/README.md
stable/gke-pvm-killer/templates/NOTES.txt
stable/gke-pvm-killer/templates/deployment.yaml

update readme, check for service account key

---

.github/PULL_REQUEST_TEMPLATE.md
stable/gke-node-pool-shifter/.helmignore
stable/gke-node-pool-shifter/Chart.yaml
stable/gke-node-pool-shifter/LICENSE
stable/gke-node-pool-shifter/OWNERS
stable/gke-node-pool-shifter/README.md
stable/gke-node-pool-shifter/templates/NOTES.txt
stable/gke-node-pool-shifter/templates/_helpers.tpl
stable/gke-node-pool-shifter/templates/clusterrole.yaml
stable/gke-node-pool-shifter/templates/clusterrolebinding.yaml
stable/gke-node-pool-shifter/templates/deployment.yaml
stable/gke-node-pool-shifter/templates/pdb.yaml
stable/gke-node-pool-shifter/templates/secret.yaml
stable/gke-node-pool-shifter/templates/service-account.yaml
stable/gke-node-pool-shifter/values.yaml
stable/gke-pvm-killer/Chart.yaml

add new chart gke-node-pool-shifter, tweak gke-pmv-killer

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/templates/deployment.yaml
stable/gcloud-sqlproxy/values.yaml

Allow to pass additional arguments like `--verbose=false` [(source)](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/cmd/cloud_sql_proxy/cloud_sql_proxy.go#L51-L92) in a way [supported by many other charts](https://github.com/helm/charts/search?p=1&q=extraArgs&unscoped_q=extraArgs)

Add extraArgs to gcloud-sqlproxy chart

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/templates/NOTES.txt
stable/gcloud-sqlproxy/templates/_helpers.tpl
stable/gcloud-sqlproxy/templates/deployment.yaml
stable/gcloud-sqlproxy/templates/gcpserviceaccount.yaml
stable/gcloud-sqlproxy/templates/pdb.yaml
stable/gcloud-sqlproxy/templates/role.yaml
stable/gcloud-sqlproxy/templates/rolebinding.yaml
stable/gcloud-sqlproxy/templates/secrets.yaml
stable/gcloud-sqlproxy/templates/serviceaccount.yaml
stable/gcloud-sqlproxy/templates/svc.yaml

If naming the release by chart name, we do not want deployment/service to be called `gcloud-sqlproxy-gcloud-sqlproxy`, all new charts have this in helper file.
Also include is preferred over template according to new charts.

Helper file ressembles modern helper file, prefer include over template

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/templates/deployment.yaml

Signed-off-by: Naseem Ullah <naseemkullah@gmail.com>
Pods generally have the release label, needed for netpol to apply to them

Needed for network policy to work

---

.circleci/config.yml
.test/e2e-kind.sh
.test/lint-charts.sh
.test/local-path-provisioner.yaml
stable/contour/Chart.yaml
stable/contour/templates/clusterrole.yaml
stable/contour/templates/crd.yaml
stable/contour/templates/deployment.yaml
stable/contour/values.yaml

update kind to v0.2.0 and contour to v0.10.0

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/values.yaml

Signed-off-by: Naseem <naseemkullah@gmail.com>
1.14 is out!
https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases/tag/1.14

[stable/gcloud-sqlproxy] Bump to 1.14

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/values.yaml

Sql proxy fix

---

stable/contour/Chart.yaml

contour 0.3.2

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/templates/deployment.yaml
stable/gcloud-sqlproxy/values.yaml

Allow users to configure annotations on the proxy pods.
Sample use case: configuring resources for an istio-proxy sidecar https://discuss.istio.io/t/override-istio-sidecar-proxy-cpu-mem-limits/3226/2

Pod annotations configuration

---

stable/hostpath-provisioner/Chart.yaml
stable/hostpath-provisioner/README.md

This lets the demo PVC work again.

Fix PVC syntax for hostpath-provisioner

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/templates/deployment.yaml
stable/gcloud-sqlproxy/values.yaml

This will allow users to configure pod priority for the proxy

Adding priorityClassName

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/templates/deployment.yaml

As explained here: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
the Deployment object is now only available in `apps/v1` apiVersion.
This apiVersion is supported since k8s 1.9.
fixes #72 
Not sure if this is a "minor" update of the chart (I don't know Helm enough to know what will happen during updgrade of the chart).
I considered that, yes it is, but I would like to have your feedback on this one ;-)
@rimusz @naseemkullah

Move deployment apiVersion to apps/v1 (supported since k8s 1.9)

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md

Update the document regarding required permissions for GCP service account, ref https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/362
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #77

[gcloud-sqlproxy] Update prerequisites in README

---

stable/hostpath-provisioner/Chart.yaml
stable/hostpath-provisioner/README.md
stable/hostpath-provisioner/templates/storageclass.yaml
stable/hostpath-provisioner/values.yaml

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #76

[hostpath-provisioner] Add support to configure reclaim policy

---

.circleci/config.yml
.test/ct.yaml
Makefile
stable/security-sample-chart/.helmignore
stable/security-sample-chart/Chart.lock
stable/security-sample-chart/Chart.yaml
stable/security-sample-chart/README.md
stable/security-sample-chart/security-mitigation.yaml
stable/security-sample-chart/templates/NOTES.txt
stable/security-sample-chart/templates/_helpers.tpl
stable/security-sample-chart/templates/database-secret.yaml
stable/security-sample-chart/templates/deployment.yaml
stable/security-sample-chart/templates/hpa.yaml
stable/security-sample-chart/templates/ingress.yaml
stable/security-sample-chart/templates/service.yaml
stable/security-sample-chart/templates/serviceaccount.yaml
stable/security-sample-chart/templates/tests/test-connection.yaml
stable/security-sample-chart/values.yaml

Add security-sample-chart

---

stable/security-sample-chart/security-mitigation.yaml

This PR adds security mitigation notes to the sample application

Updated overall mitigation summary and added mitigation notes for CVE

---

stable/security-sample-chart/Chart.yaml
stable/security-sample-chart/README.md

security-sample-chart v0.1.2

---

stable/security-sample-chart/Chart.yaml
stable/security-sample-chart/security-mitigation.yaml

security-sample-chart v0.1.3

---

stable/security-sample-chart/Chart.yaml
stable/security-sample-chart/security-mitigation.yaml

security-sample-chart-0.2.1

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/templates/deployment.yaml
stable/gcloud-sqlproxy/values.yaml

**What this PR does / why we need it**: Add support for specifying deployment strategies. It's necessary when you have defined resources for pods and you need establish deployment or update strategies different to default parameters.

Add support for specifying deployment strategy

---

Makefile

CT GA 3.0.0

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/templates/svc.yaml
stable/gcloud-sqlproxy/values.yaml

Extended service annotation for custom options, like external-dns

adding custom annotations to service.

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md

I've updated README file because there was some features missing. They were added in #98  but hasn't been mentioned in README.

add missing documentation

---

stable/hostpath-provisioner/Chart.yaml

hostpath-provisioner v0.2.13

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/templates/_helpers.tpl
stable/gcloud-sqlproxy/templates/deployment.yaml
stable/gcloud-sqlproxy/templates/gcpserviceaccount.yaml
stable/gcloud-sqlproxy/templates/horizontalpodautoscaler.yaml
stable/gcloud-sqlproxy/templates/networkpolicy.yaml
stable/gcloud-sqlproxy/templates/pdb.yaml
stable/gcloud-sqlproxy/templates/role.yaml
stable/gcloud-sqlproxy/templates/rolebinding.yaml
stable/gcloud-sqlproxy/templates/secrets.yaml
stable/gcloud-sqlproxy/templates/serviceaccount.yaml
stable/gcloud-sqlproxy/templates/svc-statefulset.yaml
stable/gcloud-sqlproxy/templates/svc.yaml
stable/gcloud-sqlproxy/values.yaml

* Adds commonLabels: User may set custom labels on all K8S objects (metadata.labels).
* Adds podLabels: User may set custom labels on the Pod level (spec.template.metadata.labels).
**Which issue this PR fixes**: fixes #117 

Added commonLabels and podLabels

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/templates/deployment.yaml
stable/gcloud-sqlproxy/values.yaml

[gcloud-sqlproxy] Added Http Health Check and Topology Constraints

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/templates/deployment.yaml

Http health check spread constraints

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/templates/deployment.yaml
stable/gcloud-sqlproxy/templates/svc.yaml
stable/gcloud-sqlproxy/values.yaml

[gcloud-sqlproxy] Simplified the topologySpreadConstraints

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/templates/deployment.yaml
stable/gcloud-sqlproxy/values.yaml

At the moment `--arg1=123` is possible to pass via extraArgs. 
additional extraFlags added for possibilities to configure with flag-like `-arg1 -arg2`

[gcloud-sqlproxy] add extraFlags (single-hyphen arguments) for command

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/README.md
stable/gcloud-sqlproxy/templates/deployment.yaml
stable/gcloud-sqlproxy/values.yaml

Support to use [cloud-sql-proxy v2](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/migration-guide.md).
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
fixes https://github.com/rimusz/charts/issues/132
--

[gcloud-sqlproxy] support cloudproxysql v2

---

stable/gcloud-sqlproxy/Chart.yaml
stable/gcloud-sqlproxy/templates/deployment.yaml

Fix error to manage multiple instances. 
Now:
```
containers:
- args:
- <project>:<region>:<instance1>?port=3306&address=0.0.0.0
<project>:<region>:<instance2>?port=3307&address=0.0.0.0
- --http-address=0.0.0.0
```
Fix:
```
containers:
- args:
- <project>:<region>:<instance1>?port=3306&address=0.0.0.0
- <project>:<region>:<instance2>?port=3307&address=0.0.0.0
- --http-address=0.0.0.0
```
I didn't declare the issue

[gcloud-sqlproxy]fix multi instances
