rimusz/charts

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/templates/pdb.yaml
https://github.com/helm/charts/tree/master/stable/gcloud-sqlproxy is marked deprecated so I'm sending the fix here.
The gcloud-sqlproxy deployment uses fullname but the PDB attempts to match by name. In my environment it meant the PDB didn't actually match anything.
=> Use fullname, not name for PDB

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/NOTES.txt, stable/gcloud-sqlproxy/templates/_helpers.tpl, stable/gcloud-sqlproxy/templates/deployment.yaml, stable/gcloud-sqlproxy/templates/gcpserviceaccount.yaml, stable/gcloud-sqlproxy/templates/secrets.yaml, stable/gcloud-sqlproxy/values.yaml
Adds support for the gcp service account controller to the sql proxy (https://github.com/kiwigrid/gcp-serviceaccount-controller). The controller will create a service account that allows access to the sql instances and inject the key into the secret.
=> Sqlproxy autogenerate service account

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/networkpolicy.yaml, stable/gcloud-sqlproxy/values.yaml
Adds the option to create a network policy.
Hi @rimusz , I've essentially copy pasted the approach of network policies from charts in the stable helm repo.
There is a caveat though, when this norm was implemented, the following was not yet possible:
https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/07-allow-traffic-from-some-pods-in-another-namespace.md
I would like to be able to allow some pods from various namespaces. Any suggestions as how to implement this? It would become the new norm, hopefully.
=> Add network policy

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/svc.yaml, stable/gcloud-sqlproxy/values.yaml
GCP has a beta feature with allow to deploy service which is available internally in GCP network, is very useful when you need to access Kubernetes service outside cluster from GCP network:
https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing
I've added feature to enable that.
=> Added option to deploy service as internal LB

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/horizontalpodautoscaler.yaml, stable/gcloud-sqlproxy/values.yaml
This PR introduces a HorizontalPodAutoscaler into the gcloud-sqlproxy helm chart. This will allow the deployment to scale according to its CPU and Memory usage against an operator defined threshold.
cc @rimusz 
n/a
n/a
=> Add a HorizontalPodAutoscaler for gcloud-sqlproxy.

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md
I tried to pass `extraArgs` to the Cloud SQL command via `helm --set` and it took me some time to figure out the syntax to specify the extraArgs map.
**Which issue this PR fixes**
This PR adds a tiny note to the Readme on how to specify `extraArgs` with `helm --set`. That's not that big of a deal and not really related to this chart in particular (basically that's the default way of specifying a map via `--set`). Nevertheless, I think it's helpful for users new to this chart  :)
If you think "this is something you should know when using helm charts and we should not document basic (or advanced) helm usage" than feel free to decline this PR :D
=> Add documentation on how to pass CloudSQL Proxy extraArgs

stable/contour/Chart.yaml, stable/contour/README.md, stable/contour/templates/service.yaml, stable/contour/values.yaml
By setting .spec.externalTrafficPolicy to Local, the client IP addresses is propagated to the end Pods.
Hi @rimusz I want to add the ability to set service externalTrafficPolicy Local to the contour service
=> Add service.externalTrafficPolicy

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/values.yaml
Update to the latest gcloud-sqlproxy. Also switches `b.gcr.io` which is now [deprecated](https://cloud.google.com/container-registry/docs/support/deprecation-notices) to `gcr.io`
**Which issue this PR fixes**
The image has a new [Dockerfile](https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/296). I don't expect any breaking changes, but probably worth looking into.
=> Bump gcloud-sqlproxy to 1.15

stable/contour/templates/clusterrolebinding.yaml
The ClusterRole binding currently uses the release name (countour.name) for ClusterRoleBinding.roleRef.name instead of the name of the ClusterRole that is actually created by the chart (contour.fullname). This will work only if the release name and the chart name are identical (so both are "contour"). This pull request corrects the roleRef name in the ClusterRoleBinding resource.
=> Use correct ClusterRole name in ClusterRoleBinding

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/values.yaml
This updates the Cloud SQL proxy to the latest version available, 1.16.
The Docker image in 1.16 now uses a distroless base image, which means a shell is not available anymore (see https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/317). However, it does not look like a shell is being used anywhere in the current chart.
=> Bumping gcloud-sqlproxy version to 1.16

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/pdb.yaml, stable/gcloud-sqlproxy/values.yaml
This addresses the issue in https://github.com/rimusz/charts/issues/44 by implementing the recommended fix for the gcloud-sqlproxy chart. Now, the PodDisruptionBudget will not get created unless there is more than one replica.
**Which issue this PR fixes**: fixes #44
I have tested this with a replica count of 1 and 2 to verify that at 1, the PDB is not created, and at 2 it is created.
=> Only create PDB for gcloud-sqlproxy if more than 1 replica

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/deployment.yaml, stable/gcloud-sqlproxy/templates/pdb.yaml, stable/gcloud-sqlproxy/values.yaml
Traditionally, lifecycle hooks (particularly `preStop`) are used to gracefully stop the container. This is particularly important when used with autoscaling, as without this, I was getting connection errors when the autoscaler scaled down the proxy deployment, as connections were terminated before the queries were completed.
With this change, someone can add in their own lifecycle hooks to ensure that the pods terminate gracefully.
This presents an issue when combined with my other PR https://github.com/rimusz/charts/pull/60 as the latest SQL proxy version does not contain a shell that can be used with the preStop hooks. I've added a note in the README to indicate this.
=> Allowing setting of lifecycle hooks on gcloud-sqlproxy to improve reliability with autoscaling

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/deployment.yaml, stable/gcloud-sqlproxy/values.yaml
One setting I found that was missing from the Chart after adjusting the `term_timeout` arg and some other values was that if I set a value longer than 30 seconds, the pod would be deleted at 30 seconds. This is because `terminationGracePeriodSeconds` is set to 30 seconds by default in Kubernetes, so any `preStop` or other process running beyond that time would be forcefully stopped.
To address this, I'm allowing that `terminationGracePeriodSeconds` value to be overridden.
Now that `terminationGracePeriodSeconds` is able to be configured, I edited some of my other comments to place less emphasis on the lifecycle hooks, as they aren't needed if `terminationGracePeriodSeconds` and `term_timeout` are both set. This …
=> Allowing terminationGracePeriodSeconds to be set for gcloud-sqlproxy

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/OWNERS, stable/gcloud-sqlproxy/templates/_helpers.tpl, stable/gcloud-sqlproxy/templates/deployment.yaml, stable/gcloud-sqlproxy/templates/gcpserviceaccount.yaml, stable/gcloud-sqlproxy/templates/horizontalpodautoscaler.yaml, stable/gcloud-sqlproxy/templates/networkpolicy.yaml, stable/gcloud-sqlproxy/templates/pdb.yaml, stable/gcloud-sqlproxy/templates/role.yaml, stable/gcloud-sqlproxy/templates/rolebinding.yaml, stable/gcloud-sqlproxy/templates/secrets.yaml, stable/gcloud-sqlproxy/templates/serviceaccount.yaml, stable/gcloud-sqlproxy/templates/svc.yaml
Modernizes the templating by providing labels helpers as per current `helm create`
I've taken the liberty of adding myself as a reviewer/maintainer to the gcloud-sqlproxy chart as it is heavily used at my org in production for almost 2 years and we plan to continue on using it, I would like to at least be notified of any PRs that come in. If you prefer not to have any additional maintainers, please let me know and I can revert those changes!
=> [stable/gcloud-sqlproxy] Labels helper

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/templates/deployment.yaml
This is needed for helm3 and beyond as per https://github.com/helm/charts/issues/19008
=> [stable/gcloud-sqlproxy] Do not set static replica count if hpa is enabled

stable/hostpath-provisioner/Chart.yaml, stable/hostpath-provisioner/README.md, stable/hostpath-provisioner/templates/deployment.yaml
Adds support for specifying a provisioner name into the chart, this is dependent on https://github.com/rimusz/hostpath-provisioner/pull/4
=> Provisioner name support

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/_helpers.tpl, stable/gcloud-sqlproxy/templates/deployment.yaml, stable/gcloud-sqlproxy/templates/gcpserviceaccount.yaml, stable/gcloud-sqlproxy/templates/rolebinding.yaml, stable/gcloud-sqlproxy/templates/secrets.yaml, stable/gcloud-sqlproxy/templates/serviceaccount.yaml, stable/gcloud-sqlproxy/values.yaml
This adds support to use a service account with only annotations to use Workload Identity https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity without the need of having a serviceAccountKey to authorize the cloud sql proxy.
Also adds support to use -ip_address_types=PRIVATE as it cannot be passed via extraArgs.
We are migrating sqlproxy from running as sidecar to running as an independent service and want to keep the use of workload identity. In our current setup, we only need to create an service account with 
```
annotations:
iam.gke.io/gcp-service-account: account-name@project-name.iam.gserviceaccount.com
```
without the need to specify serviceAccountKey.
[Place an '[x]' (no spaces) in all …
=> Add service account with Workload Identity support

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/svc.yaml, stable/gcloud-sqlproxy/values.yaml
On some cloud providers, the `Service` `spec.loadBalancerIP` field allow to assign custom IP to the load balancer created behind the scenes, like documented [here](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer)
GCP supports the `loadBalancerIP` on Internal Load Balancers, so assuming this chart is mostly installed on GCP projects, I think `loadBalancerIP` should be added to this chart's values.
=> Allow custom service loadBalancerIP

stable/gcloud-sqlproxy/Chart.yaml
**What this PR does / why we need it**: `apiVersion` is a required Chart.yaml field, its omission doesn't seem to cause runtime issues but it causes `helm lint` to fail. Using Helm v2.16.6.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
**Special notes for your reviewer**: Tested the change locally via `helm fetch --untar` to make sure that after that error is fixed, there aren't any other linting errors.  I'm not sure if this requires a Chart Version bump.
=> Add apiVersion to Chart.yaml

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/values.yaml
Signed-off-by: André Bauer <monotek23@gmail.com>
* raised livenessprobe failure threshold to 3 times the size of the readinessprobe failure threshold 
https://github.com/rimusz/charts/issues/78
=> [gcloud-sqlproxy] raised livenesss failure threshold

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/templates/svc.yaml
Let us use instanceShortName for port name, in case of having multiple instances with same name in different regions.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #81
=> [gcloud-sqlproxy] Use instanceShortName for port name when possible

stable/security-sample-chart/Chart.yaml, stable/security-sample-chart/security-mitigation.yaml
=> Security sample chart v0.1.5

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/deployment.yaml, stable/gcloud-sqlproxy/templates/svc-statefulset.yaml, stable/gcloud-sqlproxy/values.yaml
If one is deploying more than 5 DB proxies then an internal loadbalancer on google is not supported as they must have at most 5 ports.
To fix this, I added the option to deploy as statefulset which allows you to then access the proxy using the `headless` service's FQDN to get A records:
```
dig cloudsql-proxy-headless.cloudsql-proxy.svc.cluster.local
```
- [ x ] Chart Version bumped
- [ x ] Changes are documented in the README.md
=> Added Deploy as Statefulset Option

stable/hostpath-provisioner/Chart.yaml, stable/hostpath-provisioner/templates/storageclass.yaml
**What this PR does / why we need it**: 
With `storageClass: false`, helm install hostpath-provisioner still create StorageClass.
Fixes CI by the way.
**Which issue this PR fixes** *(optional)*: N/A
**Special notes for your reviewer**: N/A
=> Fixes disable StorageClass creation not effect issue

stable/hostpath-provisioner/Chart.yaml, stable/hostpath-provisioner/README.md, stable/hostpath-provisioner/templates/deployment.yaml, stable/hostpath-provisioner/values.yaml
Add nodeSelector, affinity and tolerations. I need nodeSelector and tolerations to run on amd64 nodes (not arm64) in my multi-arch cluster.
=> hostpath-provisioner: Add nodeSelector, affinity and tolerations

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/deployment.yaml, stable/gcloud-sqlproxy/values.yaml
It adds an option to configure `securityContext` of `gcloud-sqlproxy` and makes it possible to run the containers as a non-privileged user (e.g. specify `runAsUser`, `runAsGroup`, `fsGroup`...).
**Which issue this PR fixes**: none
=> Add configurable securityContext to gcloud-sqlproxy

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/templates/_helpers.tpl, stable/gcloud-sqlproxy/templates/deployment.yaml, stable/gcloud-sqlproxy/templates/svc-statefulset.yaml, stable/gcloud-sqlproxy/templates/svc.yaml
When your instance name has `-` as 15th character, it caused invalid name to be generated. This PR fixes it by trimming trailing `-`.
@rimusz @naseemkullah
=> Trim suffix dash from port name in gcloud-sqlproxy

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/pdb.yaml, stable/gcloud-sqlproxy/templates/role.yaml, stable/gcloud-sqlproxy/templates/rolebinding.yaml
Removes deprecated api usage which is removed in 1.22. New APIs available from 1.8 on.
See also https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122
This is not my code. I've just seen @cdaguerre already did the changes I was going to make but did not create a pull request to this repo.
=> Remove apis that wont work in k8s 1.22

stable/nfs-client-provisioner/Chart.yaml, stable/nfs-client-provisioner/README.md, stable/nfs-client-provisioner/templates/storageclass.yaml, stable/nfs-client-provisioner/values.yaml
Added a optional value for setting nfs-provisioner as default storage class
=> [nfs-provisioner] added default StorageClass config value

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md
Fix the documentation A quote is missing at the end of topologySpreadConstraints
=> [gcloud-sqlproxy] README: missing quote

stable/gcloud-sqlproxy/Chart.yaml
Update gcloud-sqlproxy version to 1.31.1
=> [gcloud-sqlproxy] Update gcloud-sqlproxy version to 1.31.1

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/deployment.yaml, stable/gcloud-sqlproxy/values.yaml
Might be be used to fetch instance data from ConfigMaps or Secrets and used via interpolation `$()` syntax in `cloudsql.instances[].*` helm variables.
CC: @rimusz @naseemkullah
=> [gcloud-sqlproxy] Support adding extra env variables in deployment

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/README.md, stable/gcloud-sqlproxy/templates/deployment.yaml, stable/gcloud-sqlproxy/values.yaml
* Rename the securityContext value into podSecurityContext
* Add containerSecurityContext
* Increment minor. Introducing a breaking change, should we change the major?
=> [gcloud-sqlproxy]) add security contexts

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/templates/horizontalpodautoscaler.yaml
updates hpa api 
autoscaling/v2beta1 -> autoscaling/v2
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125
autoscaling/v2 API version, available since v1.23
Maintenance support of kubernetes v.23 ended (28 Feb 2023), time to move autoscaling/v2, as it is everywhere now
=> [gcloud-sqlproxy] Update obsolete hpa api, bump app version to 1.33.4

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/templates/horizontalpodautoscaler.yaml
Fixed HorizontalPodAutoscaler to set the kind depending of the value of useStatefulset . Before it was set to Deployment no matter if you are using statefulset so it didn't work.
**Which issue this PR fixes** :
fixes #142 
=> [gcloud-sqlproxy] HPA kind depends on useStatefulset value - #142

stable/gcloud-sqlproxy/Chart.yaml, stable/gcloud-sqlproxy/templates/horizontalpodautoscaler.yaml
… sensitive  StatefulSet #142
**Which issue this PR fixes** :
fixes #142 
Stupid mistake by me in last PR since it looks like kind is case sensitive. Changed from Statefulset to StatefulSet.
I do not believe this needs a version bump.  Should remain 0.25.5 but it looks like don't have an option to just patch 0.25.5 so bumped version
Again, sorry about this, this was actually my first PR to a public repo.
=> [gcloud-sqlproxy] HPA kind Fix case sensitive StatefulSet
